/**
 * Constitution generator — analyzes the project and generates a coding
 * standards document (a "constitution") from detected conventions,
 * configured linters/formatters, project type, and existing patterns.
 *
 * The constitution is written to `.studio/CONSTITUTION.md` and injected
 * into the session context so the agent follows project conventions.
 */
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "fs"
import { join } from "path"
import { detectTooling } from "./project-detect"

const CONSTITUTION_PATH = ".studio/CONSTITUTION.md"

export interface ConstitutionInput {
  root: string
  projectName?: string
  additionalRules?: string[]
}

/** Generate a constitution from project analysis. */
export function generateConstitution(input: ConstitutionInput): string {
  const { root } = input
  const tooling = detectTooling(root)
  const sections: string[] = []

  // ——— Header ————————————————
  sections.push(`# ${input.projectName ?? tooling.projectType.ecosystem} Project Constitution\n`)
  sections.push(`Auto-generated by opencode-studio. Updated: ${new Date().toISOString()}\n`)

  // ——— Project type ————————————————
  sections.push("## Project Type\n")
  sections.push(`- **Ecosystem:** ${tooling.projectType.ecosystem}`)
  sections.push(`- **Confidence:** ${tooling.projectType.confidence}`)
  sections.push(`- **Detected markers:** ${tooling.projectType.markers.join(", ")}\n`)

  // ——— Code style ————————————————
  sections.push("## Code Style\n")
  if (tooling.formatter) {
    sections.push(`- **Formatter:** ${tooling.formatter} — format ALL code before committing`)
  }
  if (tooling.linter) {
    sections.push(`- **Linter:** ${tooling.linter} — fix all warnings before handoff`)
  }
  if (existsSync(join(root, ".editorconfig"))) {
    sections.push("- **EditorConfig present:** respect indentation, line endings, and charset settings")
  }

  // ——— Verify commands ————————————————
  sections.push("\n## Verification\n")
  const vc = tooling.verifyCommands
  if (vc.test) sections.push(`- **Tests:** \`${vc.test}\``)
  if (vc.lint) sections.push(`- **Lint:** \`${vc.lint}\``)
  if (vc.typecheck) sections.push(`- **Typecheck:** \`${vc.typecheck}\``)
  if (vc.build) sections.push(`- **Build:** \`${vc.build}\``)
  if (!vc.test && !vc.lint && !vc.typecheck && !vc.build) {
    sections.push("- No verify commands detected. Configure test/lint/build scripts.")
  }

  // ——— Conventions ————————————————
  if (tooling.conventions.length > 0) {
    sections.push("\n## Conventions\n")
    for (const conv of tooling.conventions) {
      sections.push(`- ${conv}`)
    }
  }

  // ——— Ecosystem-specific rules ————————————————
  sections.push("\n## Rules")
  const ecosystem = tooling.projectType.ecosystem
  if (ecosystem === "Rust") {
    sections.push("- Use \`clippy\` warnings as errors: \`#![deny(clippy::all)]\`")
    sections.push("- Prefer \`thiserror\` for error types, \`anyhow\` for application errors")
    sections.push("- Use \`Result<T, E>\` for fallible operations — never panic in libraries")
    sections.push("- Document public APIs with \`///\` doc comments")
  } else if (ecosystem === "Python") {
    sections.push("- Use type hints on all function signatures")
    sections.push("- Prefer \`pathlib\` over \`os.path\`")
    sections.push("- Use \`if __name__ == \"__main__\":\` guard in scripts")
    sections.push("- Docstrings on public functions (Google style)")
  } else if (ecosystem === "Go") {
    sections.push("- Run \`gofmt\` before every commit")
    sections.push("- Keep interfaces small — accept interfaces, return structs")
    sections.push("- Use \`context.Context\` for cancellation/timeout")
    sections.push("- Handle errors explicitly — no \`_ = err\`")
  } else if (ecosystem === "Bun" || ecosystem === "Node") {
    sections.push("- Use async/await — avoid raw callbacks and .then chains")
    sections.push("- One responsibility per file — split if >300 lines")
    sections.push("- Export types alongside implementations")
    sections.push("- Handle errors at the boundary — don't let raw errors reach users")
  } else if (ecosystem === "Java/Maven" || ecosystem === "Java/Gradle") {
    sections.push("- Follow Java naming conventions (camelCase methods, PascalCase classes)")
    sections.push("- Use Optional<T> instead of null where possible")
    sections.push("- Document public APIs with Javadoc")
  }

  // ——— User rules ————————————————
  if (input.additionalRules?.length) {
    sections.push("\n## Additional Rules")
    for (const rule of input.additionalRules) {
      sections.push(`- ${rule}`)
    }
  }

  // ——— General quality rules ————————————————
  sections.push("\n## Quality Rules")
  sections.push("- Write tests FIRST (TDD) — tests exist before implementation")
  sections.push("- Handle edge cases: empty input, boundary values, error paths")
  sections.push("- No commented-out code in commits")
  sections.push("- No TODO/FIXME without an associated task or issue")
  sections.push("- Run studio_verify before every handoff")
  sections.push("- Keep functions under 50 lines — extract if longer")

  return sections.join("\n")
}

/** Write the constitution to `.studio/CONSTITUTION.md`. */
export function writeConstitution(root: string, content: string): string {
  const path = join(root, CONSTITUTION_PATH)
  const dir = join(root, ".studio")
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  writeFileSync(path, content, "utf-8")
  return path
}

/** Check if a constitution exists. */
export function constitutionExists(root: string): boolean {
  return existsSync(join(root, CONSTITUTION_PATH))
}

/** Read the constitution for injection into session context. */
export function readConstitution(root: string): string | null {
  try {
    if (!constitutionExists(root)) return null
    return readFileSync(join(root, CONSTITUTION_PATH), "utf-8")
  } catch {
    return null
  }
}

/**
 * Get the constitution as a context block for the session.
 * If no constitution exists, returns null (don't auto-generate — let the user choose).
 */
export function constitutionContextBlock(root: string): string | null {
  const content = readConstitution(root)
  if (!content) return null
  // Truncate to keep context budget reasonable.
  const max = 4000
  const truncated = content.length > max ? `${content.slice(0, max)}\n\n…(truncated — see .studio/CONSTITUTION.md)` : content
  return `[studio constitution]\n${truncated}`
}
